// Generated by CoffeeScript 1.12.2
Phacker.Game.Waterlilies = (function() {
  function Waterlilies(gm) {
    this.gm = gm;
    this._fle_ = 'Waterlilies';
    this.glob = ge.parameters;
    this.glob.wly = {
      x0: gameOptions.fullscreen ? this.glob.bg.w - 85 : this.glob.bg.w - 250,
      y0: this.glob.bg.h + 20,
      h0: 4,
      s0: .65,
      dxmax: 275,
      dymax: 162
    };
    this.wls = [];
    this.make_lilie();
    this.make_lilie();
  }

  Waterlilies.prototype.make_lilie = function() {
    var hxys, l, x0, y0;
    if (this.wls.length === 0) {
      return this.wls.push(new Phacker.Game.One_waterlily(this.gm, {
        h: this.glob.wly.h0,
        x: this.glob.wly.x0,
        y: this.glob.wly.y0,
        s: this.glob.wly.s0
      }));
    } else {
      l = this.wls.length;
      x0 = this.wls[l - 1].position.bottom.x;
      y0 = this.wls[l - 1].position.bottom.y;
      hxys = this.hxy_scale(this.glob.wly.x0, this.glob.wly.y0);
      return this.wls.push(new Phacker.Game.One_waterlily(this.gm, hxys));
    }
  };

  Waterlilies.prototype.hxy_scale = function(x0, y0) {
    var dx, x, y;
    dx = this.gm.rnd.integerInRange(0, 2);
    dx = (3 + dx) * this.glob.wly.dxmax / 7;
    x = x0 - dx;
    y = y0 - this.glob.wly.dymax / this.glob.wly.dxmax * dx;
    return {
      h: 4,
      x: x,
      y: y,
      s: this.glob.wly.s0
    };
  };

  return Waterlilies;

})();
